// <auto-generated />
using Diyokee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diyokee.Migrations
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20260909151538_Rename child tables and their foreign key")]
    partial class Renamechildtablesandtheirforeignkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Diyokee.DFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("BPM")
                        .HasColumnType("REAL");

                    b.Property<double>("DownbeatAt")
                        .HasColumnType("REAL");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasReplayGain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReplayGain")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Waveform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Diyokee.DFile+BeatGridMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BPM")
                        .HasColumnType("REAL");

                    b.Property<int?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDownbeat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReference")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Position")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("BeatGridMarkers", (string)null);
                });

            modelBuilder.Entity("Diyokee.DFile+CuePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Position")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("CuePoints", (string)null);
                });

            modelBuilder.Entity("Diyokee.DFile+BeatGridMarker", b =>
                {
                    b.HasOne("Diyokee.DFile", null)
                        .WithMany("BeatGridMarkers")
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("Diyokee.DFile+CuePoint", b =>
                {
                    b.HasOne("Diyokee.DFile", null)
                        .WithMany("CuePoints")
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("Diyokee.DFile", b =>
                {
                    b.Navigation("BeatGridMarkers");

                    b.Navigation("CuePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
