namespace Diyokee {
    public class AudioDevice(string name, List<AudioDevice.AudioChannel> channels) {
        public enum AudioChannel {
            FrontStereo,
            FrontLeft,
            FrontRight,

            SideStereo,
            SideLeft,
            SideRight,

            RearStereo,
            RearLeft,
            RearRight,

            CenterAndLFE,
            Center,
            LFE,

            Out_0,
            Out_1,
            Out_2,
            Out_3,
            Out_4,
            Out_5,
            Out_6,
            Out_7,
            Out_8,
            Out_9,
            Out_10,
            Out_11,
            Out_12,
            Out_13,
            Out_14,
            Out_15,
            Out_16,
            Out_17,
            Out_18,
            Out_19,
            Out_20,
            Out_21,
            Out_22,
            Out_23,
            Out_24,
            Out_25,
            Out_26,
            Out_27,
            Out_28,
            Out_29,
            Out_30,
            Out_31,
            Out_32,
            Out_33,
            Out_34,
            Out_35,
            Out_36,
            Out_37,
            Out_38,
            Out_39,
            Out_40,
            Out_41,
            Out_42,
            Out_43,
            Out_44,
            Out_45,
            Out_46,
            Out_47,
            Out_48,
            Out_49,
            Out_50,
            Out_51,
            Out_52,
            Out_53,
            Out_54,
            Out_55,
            Out_56,
            Out_57,
            Out_58,
            Out_59,
            Out_60,
            Out_61,
            Out_62,
            Out_63,
            Out_64,
            Out_65,
            Out_66,
            Out_67,
            Out_68,
            Out_69,
            Out_70,
            Out_71,
            Out_72,
            Out_73,
            Out_74,
            Out_75,
            Out_76,
            Out_77,
            Out_78,
            Out_79,
            Out_80,
            Out_81,
            Out_82,
            Out_83,
            Out_84,
            Out_85,
            Out_86,
            Out_87,
            Out_88,
            Out_89,
            Out_90,
            Out_91,
            Out_92,
            Out_93,
            Out_94,
            Out_95,
            Out_96,
            Out_97,
            Out_98,
            Out_99,
        }

        public string Name { get; set; } = name;
        public List<AudioChannel> Channels { get; set; } = channels;

        public AudioDevice(string name, AudioChannel channel) : this(name, [channel]) {}
        public AudioDevice(string name) : this(name, [AudioChannel.FrontStereo]) { }
        public AudioDevice() : this("", []) { }
    }
}